### PR TITLE
Iup sample fix

### PR DESCRIPTION
**Pull request by lkppo**
Hello,

This pull-request provides a fix to IUP samples for 64 bit compliance and a clean use of attributs setting with a byValue parameter.

What's your prefered entry point for contribs? Github repository, SF repository, other, pull-request, formated patch...?

I intend to contrib an update of IUP binding. Does anyone already work on this subject?

Regards,

-- 
LkpPo

### CODE REVIEW

**Comment by rversteegen** [comment]
I am not certain, but aren't FB bindings, including for IUP, generated with fbfrog, using the scripts in the fbbindings repository at https://github.com/dkl/fbbindings ?
If so, manually editing bindings instead of running the fbbindings script would be a good way to waste your time: there's a good chance you wouldn't need to do anything else in order to generate updated bindings.
However I see that dkl has marked that repository unmaintained.

None of that relates to this pull request, which is for the samples.

**Comment by lkppo** [comment]
I'm a newcomer and don't know that. It would be a very good news if bindings are done with fbfrog. https://github.com/dkl/fbbindings is tagged UNMAINTAINED. What's the real status of this project?

**Comment by jayrm** [comment]
The creator of fbfrog, dkl, is currently not maintaining the project.  However, the project is still valid in that the last set of fbc header/library bindings was created using the project.  Ideally, we (developers and user community) would continue to build on the work already done, updating the source build.

**Comment by rversteegen** [comment]
OK thanks.

Can this be merged? It looks fine to me. Although I don't know IUP and didn't test this change.

**Comment by lkppo** [comment]
Thanks!

I tried to update fbbindings packages with a cygwin 64bits env. and hit a lot of broken things.

Maybe cygwin is not the right build env. for this task.

It seems also that fbfrog have been changed and the makefile rules are not in sync with fbfrog. Some rules are broken, others don't output the same bi files, others output empty bi files.

If someone has commit rights I can send a PR for broken links and minors things for starting.

An other place to talk about this?

Regards,

**Comment by dkl** [comment]
Yea, it would be better to talk about this in the forum. I might be able to help with some points.

**Comment by lkppo** [comment]
I re-posted at https://www.freebasic.net/forum/viewforum.php?f=14

**Pull request merged**
