### PR TITLE
Add Small GUI Library

### PR DESCRIPTION
**Pull request by 3oheicrw**
Small GUI Library created by Henri Serindat, FreeBASIC binding created by ruanjiaxing and updated by 3oheicrw.

https://github.com/ruanjiaxing/SGL-FreeBASIC

https://github.com/3oheicrw/SGL-FreeBASIC

Please note I don't know how to update fbc/readme.txt. Please update it if needed. Thanks.

### CODE REVIEW

**Comment by 3oheicrw** [comment]
> Topic disapproved:
> 
> "Pull request #358"
> 
> Forum: Community Discussion
> 
> Reason: The reported message does not fit into any other category, please use the further information field. Yet another duplicated account of operator+/freeCish/miilvyxg/others.
> 
> Mar 21, 2022 14:51

I'm neither operator+ nor freeCish nor miilvyxg. I don't know that person. Please have a look at my pull request. It seems there is no one look after this place. Too silent.

**Comment by jayrm** [comment]
Is the original library still supported / developed?  This does not seem to be a popular library, and if you are willing to support freebasic bindings, what is the motivation to include with freebasic distribution?

**Comment by 3oheicrw** [comment]
> Is the original library still supported / developed? This does not seem to be a popular library, and if you are willing to support freebasic bindings, what is the motivation to include with freebasic distribution?

The motivation is trying to save it. The last version of SGL is from 2020. It seems to be very stable. On it homeland the Pelles C community no one seems to use it other than it author. I found the library to be beautiful and I don't want it to fade over time. It can help the development with Windows API easier on FreeBASIC, too. It's only a thin wrapper over the Windows API so it's very lightweight and I think don't cost much to add.

**Comment by jayrm** [comment]
If you want to generate interest try posting in the [Libraries & Headers](https://www.freebasic.net/forum/viewforum.php?f=14) to provide examples of usage and links to source and binary resources.

**Pull request closed without merging**
